env:
  contexts:
    - name: "juice-shop-context"
      urls:
        - "http://juice-shop:3000"
      authentication:
        method: "form"
        parameters:
          loginUrl: "http://juice-shop:3000/rest/user/login"
          loginRequestData: "email={%username%}&password={%password%}"
      users:
        - name: "admin"
          credentials:
            username: "admin@juice-sh.op"
            password: "admin123"

jobs:
  - type: "spider"
    parameters:
      context: "juice-shop-context"
      user: "admin"
      maxDuration: 60
  - type: "passiveScan-wait"
    parameters:
      maxDuration: 10
  - type: "report"
    parameters:
      template: "traditional-json"
      reportDir: "/zap/wrk"
      reportFile: "authenticated_report.json"
      reportTitle: "ZAP Security Report"
      reportDescription: "Automated security scan report"
